title: Git Workshop
description: A comprehensive guide to Git from basics to advanced collaboration
baseurl: "/git_software_dev_workshop"
url: "https://shmouses.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
navigation:
  - title: Home
    url: /git_software_dev_workshop/
  - title: Basic Concepts
    url: /git_software_dev_workshop/01_basic_concepts/01_introduction/
  - title: Advanced Concepts
    url: /git_software_dev_workshop/02_advanced_concepts/01_branching/
  - title: Team Collaboration
    url: /git_software_dev_workshop/03_team_collaboration/01_forking_and_remote/
  - title: Project Management
    url: /git_software_dev_workshop/04_project_management/01_git_for_leaders/
  - title: Exercises
    url: /git_software_dev_workshop/exercises/python_project/

# Collections
collections:
  basic_concepts:
    output: true
    permalink: /01_basic_concepts/:path/
  advanced_concepts:
    output: true
    permalink: /02_advanced_concepts/:path/
  team_collaboration:
    output: true
    permalink: /03_team_collaboration/:path/
  project_management:
    output: true
    permalink: /04_project_management/:path/
  exercises:
    output: true
    permalink: /exercises/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "basic_concepts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "advanced_concepts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "team_collaboration"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "project_management"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "exercises"
    values:
      layout: "default" 